import type { Metadata } from 'next/types'

import React from 'react'

export default function PrivacyPolicyPage() {
  return (
    <div className="pt-24 pb-24">
      <div className="container mb-16">
        <div className="prose dark:prose-invert max-w-[50rem] mx-auto">
          <h1>Privacy Policy</h1>
          <p>
            <strong>Last updated:</strong> 10 August 2026
          </p>

          <h2>1. Who we are</h2>
          <p>
            This website is operated by a sole trader (natural person) providing financial
            coaching services (&ldquo;we&rdquo;, &ldquo;us&rdquo;). We are the data controller
            responsible for your personal data under the EU General Data Protection Regulation
            (GDPR).
          </p>
          <p>
            Contact: <a href="mailto:pauliusmiecius1@gmail.com">pauliusmiecius1@gmail.com</a>
          </p>

          <h2>2. What data we collect</h2>
          <ul>
            <li>
              <strong>Booking &amp; order data:</strong> your name, email address, the service
              booked, appointment date/time, and payment status (amount, currency, and Stripe
              checkout/payment identifiers). We never see or store your full card details &mdash;
              these are handled directly by Stripe.
            </li>
            <li>
              <strong>Contact/form submissions:</strong> any details you submit through a contact
              or enquiry form on this site (e.g. name, email, message).
            </li>
            <li>
              <strong>Technical data:</strong> standard web server logs generated by our hosting
              provider (Vercel) when you visit the site.
            </li>
          </ul>
          <p>
            We do not use analytics, advertising, or tracking cookies. We only use strictly
            necessary cookies required for the site and checkout to function.
          </p>

          <h2>3. Why we process your data (lawful basis)</h2>
          <ul>
            <li>
              <strong>Contract performance:</strong> to process your booking, take payment, and
              deliver the service you requested.
            </li>
            <li>
              <strong>Legitimate interests:</strong> to respond to enquiries submitted through our
              contact forms and to keep our records of past sessions.
            </li>
            <li>
              <strong>Legal obligation:</strong> to keep financial/transaction records as required
              by applicable tax and accounting law.
            </li>
          </ul>

          <h2>4. Who we share your data with</h2>
          <p>
            We share the minimum data necessary with the following processors, solely to operate
            this service:
          </p>
          <ul>
            <li>
              <strong>Stripe</strong> &mdash; payment processing (receives your name, email, and
              card details directly; we never handle your card details).
            </li>
            <li>
              <strong>Vercel</strong> &mdash; website hosting, file storage, and infrastructure.
            </li>
            <li>Our database provider &mdash; secure storage of booking and order records.</li>
          </ul>
          <p>We do not sell your personal data or share it with anyone for marketing purposes.</p>

          <h2>5. How long we keep your data</h2>
          <p>
            We retain booking and order records for as long as needed to deliver the service and
            to comply with our legal/tax record-keeping obligations (typically up to 7 years for
            financial records). Contact form submissions are kept only as long as needed to
            respond to and resolve your enquiry, after which they are deleted.
          </p>

          <h2>6. Your rights</h2>
          <p>Under the GDPR, you have the right to:</p>
          <ul>
            <li>access the personal data we hold about you;</li>
            <li>request correction of inaccurate data;</li>
            <li>request erasure of your data, where we are not legally required to keep it;</li>
            <li>request restriction of, or object to, our processing of your data;</li>
            <li>request a copy of your data in a portable format; and</li>
            <li>
              lodge a complaint with your local data protection supervisory authority.
            </li>
          </ul>
          <p>
            To exercise any of these rights, email{' '}
            <a href="mailto:pauliusmiecius1@gmail.com">pauliusmiecius1@gmail.com</a>. We will
            respond within one month, as required by the GDPR.
          </p>

          <h2>7. Data security</h2>
          <p>
            We use industry-standard measures to protect your data, including encrypted
            connections (HTTPS), access-controlled databases, and payment processing that never
            exposes your full card details to us.
          </p>

          <h2>8. Changes to this policy</h2>
          <p>
            We may update this policy from time to time. Material changes will be reflected by
            updating the &ldquo;Last updated&rdquo; date above.
          </p>
        </div>
      </div>
    </div>
  )
}

export function generateMetadata(): Metadata {
  return {
    title: 'Privacy Policy',
    description: 'How we collect, use, and protect your personal data.',
  }
}
